#!/usr/bin/env bash

# Set up OS X how I like it.
# 
# This list is limited Preferences I know how to set via the command line (basically, those I've found on the web).  It'd probably be easy to figure out how to do others, but...  meh.
# 
# Author: Benjamin Oakes <hello@benjaminoakes.com>

if [ 'Darwin' == `uname` ]; then
  echo "Applying OS X preferences..."
  # defaults write /Library/Preferences/com.apple.loginwindow DesktopPicture '/Library/Desktop Pictures/200820013814-5543.jpg'
  defaults write com.apple.dashboard mcx-disabled -boolean YES
  defaults write com.apple.dock no-bouncing -bool TRUE
  defaults write com.apple.dock persistent-others -array-add '{ "tile-data" = { "list-type" = 1; }; "tile-type" = "recents-tile"; }'
  defaults write com.apple.Dock showhidden -bool YES
  defaults write com.apple.iCal IncludeDebugMenu YES
  defaults write com.apple.iTunes invertStoreLinks -bool YES
  defaults write com.apple.iTunes full-window -1 # No more vertical window controls in iTunes 10
  defaults write com.apple.QuickTimePlayerX MGFullScreenExitOnAppSwitch 0
  defaults write com.apple.safari IncludeDebugMenu 1
  defaults write com.apple.screencapture location $HOME/Outbox/
  defaults write -g NSNavPanelExpandedStateForSaveMode -bool TRUE

  # Maximize horizontally and vertically when clicking zoom
  defaults write org.vim.MacVim MMZoomBoth -boolean YES
  # # Open new files in the current window instead of in a new window:
  # defaults write org.vim.MacVim MMOpenFilesInTabs 1
else
  echo "Not running on Mac OS X -- ignoring..."
fi

