#!/usr/bin/env bash
# Author: Benjamin Oakes <hello@benjaminoakes.com>

if [ 'Linux' == `uname` ]; then
  ln -s $HOME/.local/share/Trash/files/ $HOME/.Trash
else
  echo "Not running on Linux -- ignoring..."
fi

