#!/usr/bin/env bash

# GNOME (Ubuntu) settings.
#
# Author: Benjamin Oakes <hello@benjaminoakes.com>

if [ 'Linux' == `uname` ]; then
  ln -s $HOME/.local/share/Trash/files/ $HOME/.Trash
else
  echo "Not running on Linux -- ignoring..."
fi

# I'm not sure, but I think this stops the notification about program updates from popping up.  *Seriously*, it comes up almost every day.  I'd rather just update en masse once a month like with Windows or OS X.)
gconftool -s --type bool /apps/update-notifier/auto_launch false
