#!/usr/bin/env ruby

# Install (or update) the dotfiles for the current user while still keeping them under version control.  This is done using symlinks.  The dotfiles can be made current by moving to the checkout directory and then updating this copy (using `git pull`).  Do not remove the checkout directory.
# 
# NOTE This script must be run from the directory in which the source dotfiles are contained (i.e. where you found this file, most likely).
# 
# Author: Benjamin Oakes <hello@benjaminoakes.com>

require 'fileutils'

HOME = File.expand_path('~') + '/'
current_directory = Dir.new('.')

THIS_FILE = File.basename(__FILE__)

IGNORED = [
  '.',
  '..',
  '.DS_Store',
  '.git',
  '.gitignore',
  'defaults',
  'gnome_settings',
  'compiz_config.profile',
  'README.md',
  THIS_FILE,
  ".#{THIS_FILE}.swp",
]

current_directory.entries.each do |entry|
  unless IGNORED.any? { |ignored| entry == ignored }
    filename = File.expand_path(entry)
    dotfilename = HOME + '.' + entry

    # It doesn't seem like .forward is recognized correctly as a symlink.  Since it's small and almost never changes, just copy it instead.
    if 'forward' == entry
      FileUtils.copy(filename, dotfilename)
      puts "Copied '#{filename}' to '#{dotfilename}'"
    else
      begin
        File.symlink(filename, dotfilename)
        puts "Installed '#{filename}' as '#{dotfilename}'"
      rescue Errno::EEXIST
        puts "WARNING: '#{dotfilename}' already exists and was not overwritten"
      end
    end
  end
end

# Settings-applying scripts for various OSes.  (See each file for details.)
puts %x(bash ./defaults) # Using sh confuses `[`
puts %x(bash ./gnome_settings) # Using sh confuses `[`

